sudo: required

services:
  - docker

before_install:
  - docker build -t richaddo/dev-client -f ./client/Dockerfile.dev ./client

script: docker run -e CI=true richaddo/dev-client npm run test -- --coverage

after_success:
  - docker build -t richaddo/prod-client ./client
  - docker build -t richaddo/prod-server ./server
  - docker build -t richaddo/nginx ./nginx
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub
  - docker push richaddo/prod-client
  - docker push richaddo/nginx
  - docker push richaddo/prod-server
