services:
  mongo:
    image: mongo
    restart: always
    env_file: ./server/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - "27017:27017"
  api:
    depends_on:
      - mongo
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file: ./server/.env
    volumes:
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
    environment:
      - ME_CONFIG_MONGODB_URL={MONGODB_URI}
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ./client:/usr/src/app
