services:
  mongo:
    image: mongo
    restart: always
    env_file: ./server/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27017:27017"
  server:
    build: ./server/Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
