services:
  mongo:
    image: mongo
    # restart: always
    env_file: ./server/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=temple4b
      - MONGO_INITDB_ROOT_PASSWORD=okX5u1gadErGcuer
    ports:
      - "27017:27017"
  server:
    depends_on:
      - mongo
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file: ./server/.env
    volumes:
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
    ports:
      - "3001:3001"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb+srv://temple4b:okX5u1gadErGcuer@cluster0.5vebfpi.mongodb.net/movieDB
