name: Entertainment-app CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clear npm cache and reinstall
        run: |
          rm -rf node_modules
          npm cache clean -f

      - name: Install Dependencies
        working-directory: ./client
        run: |
          npm install

      - name: Run Tests
        working-directory: ./client
        run: npm test
